mysql:
  username: ${DATABASE_MYSQL_USERNAME:root}
  password: ${DATABASE_MYSQL_PASSWORD:123456}
  schema: ${DATABASE_MYSQL_SCHEMA:adm_videos}
  url: ${DATABASE_MYSQL_UR:localhost:3306}

  spring:
    jpa:
      show-sql: false
      hibernate:
        ddl-auto: none